//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.29 at 01:51:16 오후 KST 
//


package com.mall.interfaces.frm.util;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ProductItmLstVO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ProductItmLstVO">
 *   &lt;complexContent>
 *     &lt;extension base="{com.lton.interfaces.vo}LtonCommonVO">
 *       &lt;sequence>
 *         &lt;element name="eitmNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="sortSeq" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="dpYn" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="itmOptLst" type="{com.lton.interfaces.vo}ProductItmOptLstVO" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="itmImgLst" type="{com.lton.interfaces.vo}ProductItmImgLstVO" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="clrchipLst" type="{com.lton.interfaces.vo}ProductClrchipLstVO" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="pdUtStdInfo" type="{com.lton.interfaces.vo}ProductPdUtStdInfoVO"/>
 *         &lt;element name="slPrc" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="afflSupPmct" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="afflMrgnRt" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="afflLwstMrgnRt" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="salesAwarNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="stkQty" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ProductItmLstVO", propOrder = {
    "eitmNo",
    "sortSeq",
    "dpYn",
    "itmOptLst",
    "itmImgLst",
    "clrchipLst",
    "pdUtStdInfo",
    "slPrc",
    "afflSupPmct",
    "afflMrgnRt",
    "afflLwstMrgnRt",
    "salesAwarNo",
    "stkQty"
})
public class ParentVo
    extends LtonCommonVO
{

    @XmlElement(required = true)
    protected String eitmNo;
    protected List<ChildVo> itmOptLst;
    protected Long slPrc;

    /**
     * Gets the value of the eitmNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEitmNo() {
        return eitmNo;
    }

    /**
     * Sets the value of the eitmNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEitmNo(String value) {
        this.eitmNo = value;
    }

    /**
     * Gets the value of the itmOptLst property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the itmOptLst property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getItmOptLst().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ChildVo }
     * 
     * 
     */
    public List<ChildVo> getItmOptLst() {
        if (itmOptLst == null) {
            itmOptLst = new ArrayList<ChildVo>();
        }
        return this.itmOptLst;
    }

    /**
     * Gets the value of the slPrc property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getSlPrc() {
        return slPrc;
    }

    /**
     * Sets the value of the slPrc property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setSlPrc(Long value) {
        this.slPrc = value;
    }
}
